name: Build KernelPatch Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Run Make
        run: |
          # Point the Makefile to the installed Android NDK path
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
          
          # Compile using the Makefile target
          make clean
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selinux_hook_kpm
          path: "*.kpm"
