name: Build KernelPatch Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build Module
        run: |
          NDK_BIN=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          
          # Pass local KernelPatch directory to Makefile
          make clean || true
          make \
            KP_DIR=$(pwd)/KernelPatch \
            NDK_PATH=$NDK_BIN \
            CC=$NDK_BIN/aarch64-linux-android31-clang \
            OBJCOPY=$NDK_BIN/llvm-objcopy

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selinux_hook_kpm
          path: "*.kpm"
